import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        absolute: 'First blog'
    },
    description: "Generated by create next app",
};

export default function FirstBlog() {
    return <h1>First blog</h1>
}