import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Blogs',
    description: "Generated by create next app",
};
export default async function Blog() {
    await new Promise(resolve => setTimeout(resolve, 2000));
    return <h1>My Blog</h1>
}