import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Blogs',
    description: "Generated by create next app",
};
export default function Blog() {
    return <h1>My Blog</h1>
}